# Generated by Django 4.2.5 on 2023-10-10 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawldetail',
            name='fetch_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crawllist',
            name='fetch_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='crawldetail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='crawllist',
            table=None,
        ),
    ]
