# Generated by Django 4.2.5 on 2023-10-17 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0002_alter_crawldetail_fetch_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crawldetail",
            name="jigyosyo_code",
        ),
        migrations.AddField(
            model_name="crawldetail",
            name="crawl_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="crawler.crawllist",
            ),
        ),
    ]
