import {
  KEIKEI_KUBUN_CHOICES,
  SUPPORT_STATUS_CHOICES,
  SUPPORT_MEANS_CHOICES,
} from "./label-choices";

export const TRANSACTION_FIELDS = [
  // CharField, DateField, TextField, FileField

  { name: "visit_date", label: "訪問日", isDisplay: true, type: "date" },
  { name: "visit_memo", label: "訪問メモ", isDisplay: true, type: "text" },
  { name: "file", label: "ファイル", isDisplay: true, type: "file" },

  // CharField with choices
  {
    name: "support_means",
    label: "支援方法",
    isDisplay: true,
    type: "select",
    options: SUPPORT_MEANS_CHOICES,
  },
  {
    name: "keikei_kubun",
    label: "系型区分",
    isDisplay: true,
    type: "select",
    options: KEIKEI_KUBUN_CHOICES,
  },
  {
    name: "support_status",
    label: "支援状況",
    isDisplay: true,
    type: "select",
    options: SUPPORT_STATUS_CHOICES,
  },

  // BooleanField
  {
    name: "is_under_fifty",
    label: "５０人以下",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "事業所情報",
  },
  {
    name: "is_before_establishment",
    label: "開業前",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "事業所情報",
  },
  {
    name: "is_within_three_years_since_estabrishment",
    label: "開業三年未満",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "事業所情報",
  },
  {
    name: "is_dedicated",
    label: "専任済み",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "雇用管理責任者",
  },
  {
    name: "is_participated",
    label: "過去に受講者有",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "雇用管理責任者",
  },
  {
    name: "is_recruiting_on_hw",
    label: "ＨＷに募集中",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "情報収集",
    mLabelGroup: "関係機関への情報提供",
  },
  {
    name: "is_going_to_recruit",
    label: "募集予定",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "情報収集",
    mLabelGroup: "関係機関への情報提供",
  },
  {
    name: "is_recruiting_on_expect_hw",
    label: "ＨＷ以外に募集予定",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "情報収集",
    mLabelGroup: "関係機関への情報提供",
  },
  {
    name: "is_accepting_intern",
    label: "介護実習の受入",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "情報収集",
    mLabelGroup: "関係機関への情報提供",
  },
  {
    name: "will_inform_hw",
    label: "労働局（ＨＷ）",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "伝達先",
    mLabelGroup: "関係機関への情報提供",
  },
  {
    name: "will_inform_prefecture",
    label: "都道府県",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "伝達先",
    mLabelGroup: "関係機関への情報提供",
  },
  {
    name: "will_inform_others",
    label: "その他の関係機関",
    isDisplay: true,
    type: "checkbox",
    sLabelGroup: "伝達先",
    mLabelGroup: "関係機関への情報提供",
  },
  {
    name: "done_explain_support",
    label: "支援メニューの説明",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "with_tool_utilization",
    label: "ツールの活用",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "done_knowing_problem",
    label: "課題の把握",
    isDisplay: true,
    type: "checkbox",
  },

  {
    name: "with_employment_consultant",
    label: "雇用コンサル",
    sLabelGroup: "専門家との同行",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "with_health_counselor",
    label: "ヘルスカウンセラー",
    sLabelGroup: "専門家との同行",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "with_training_coordinator",
    label: "研修コーディネーター",
    sLabelGroup: "専門家との同行",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "with_alone_on_hw",
    label: "単独",
    sLabelGroup: "労働局・ＨＷからの情報提供",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "with_staff_on_hw",
    label: "同行",
    sLabelGroup: "労働局・ＨＷからの情報提供",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_job_posting_consult",
    label: "相談",
    sLabelGroup: "求人求職",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_job_posting_inform",
    label: "情報",
    sLabelGroup: "求人求職",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_working_conditions_consult",
    label: "相談",
    sLabelGroup: "労働条件",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_working_conditions_inform",
    label: "情報",
    sLabelGroup: "労働条件",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_welfare_benefits_consult",
    label: "相談",
    sLabelGroup: "福利厚生",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_welfare_benefits_inform",
    label: "情報",
    sLabelGroup: "福利厚生",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_workplace_communication_consult",
    label: "相談",
    sLabelGroup: "職場のコミュニケーション",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_workplace_communication_inform",
    label: "情報",
    sLabelGroup: "職場のコミュニケーション",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_subsidies_consult",
    label: "相談",
    sLabelGroup: "助成金",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_subsidies_inform",
    label: "情報",
    sLabelGroup: "助成金",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_care_services_consult",
    label: "相談",
    sLabelGroup: "介護サービス",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_care_services_inform",
    label: "情報",
    sLabelGroup: "介護サービス",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_workplace_environment_consult",
    label: "相談",
    sLabelGroup: "職場環境",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_workplace_environment_inform",
    label: "情報",
    sLabelGroup: "職場環境",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_skill_development_consult",
    label: "相談",
    sLabelGroup: "能力開発",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_skill_development_inform",
    label: "情報",
    sLabelGroup: "能力開発",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_employment_management_responsibility_consult",
    label: "相談",
    sLabelGroup: "雇用管理責任者関係",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_employment_management_responsibility_inform",
    label: "情報",
    sLabelGroup: "雇用管理責任者関係",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_other_consult",
    label: "相談",
    sLabelGroup: "その他",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "koyou_other_inform",
    label: "情報",
    sLabelGroup: "その他",
    mLabelGroup: "雇用管理に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  // ... 能力開発に関する項目
  {
    name: "noukai_qualification_system_training_consult",
    label: "相談",
    sLabelGroup: "資格制度・研修情報等",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_qualification_system_training_inform",
    label: "情報",
    sLabelGroup: "資格制度・研修情報等",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_job_posting_consult",
    label: "相談",
    sLabelGroup: "求人・求職関係",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_job_posting_inform",
    label: "情報",
    sLabelGroup: "求人・求職関係",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_training_plan_curriculum_consult",
    label: "相談",
    sLabelGroup: "研修計画・カリキュラムの策定",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_training_plan_curriculum_inform",
    label: "情報",
    sLabelGroup: "研修計画・カリキュラムの策定",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_subsidy_system_for_skill_development_consult",
    label: "相談",
    sLabelGroup: "能力開発に係る助成制度関係",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_subsidy_system_for_skill_development_inform",
    label: "情報",
    sLabelGroup: "能力開発に係る助成制度関係",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_vocational_skill_development_promoter_consult",
    label: "相談",
    sLabelGroup: "職業能力開発推進者関係",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_vocational_skill_development_promoter_inform",
    label: "情報",
    sLabelGroup: "職業能力開発推進者関係",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_other_skill_development_consult",
    label: "相談",
    sLabelGroup: "その他",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
  {
    name: "noukai_other_skill_development_inform",
    label: "情報",
    sLabelGroup: "その他",
    mLabelGroup: "能力開発に係る支援",
    isDisplay: true,
    type: "checkbox",
  },
].map((field) => ({
  ...field,
  groupId: field.sLabelGroup || field.groupId,
}));

export const AUXILIARY_FIELDS = [
  {
    name: "_jigyosyo_code",
    label: "事業所コード",
    isDisplay: true,
    type: "text",
  },
  {
    name: "_jigyosyo_custom_code",
    label: "支部独自コード",
    isDisplay: true,
    type: "text",
  },
  { name: "_company_name", label: "法人名", isDisplay: true, type: "text" },
  { name: "_jigyosyo_name", label: "事業所名", isDisplay: true, type: "text" },
  {
    name: "_company_type",
    label: "法人種別",
    isDisplay: true,
    type: "text",
  },
  {
    name: "_jigyosyo_postal_code",
    label: "事業所郵便番号",
    isDisplay: true,
    type: "text",
  },
  {
    name: "_jigyosyo_address",
    label: "事業所住所",
    isDisplay: true,
    type: "text",
  },
  {
    name: "_jigyosyo_tel_number",
    label: "事業所電話番号",
    isDisplay: true,
    type: "text",
  },
  {
    name: "_jigyosyo_fax_number",
    label: "事業所FAX番号",
    isDisplay: true,
    type: "text",
  },
  {
    name: "_jigyosyo_repr_name",
    label: "代表者名",
    isDisplay: true,
    type: "text",
  },
  {
    name: "_jigyosyo_repr_position",
    label: "事業所代表者役職",
    isDisplay: false,
    type: "text",
  },
  {
    name: "_jigyosyo_kourou_url",
    label: "厚生労働省URL",
    isDisplay: false,
    type: "text",
  },
  {
    name: "_jigyosyo_kourou_release_datetime",
    label: "事業所公労リリース日時",
    isDisplay: false,
    type: "text",
  },
  {
    name: "_jigyosyo_number_of_member",
    label: "職員数",
    isDisplay: false,
    type: "text",
  },
  {
    name: "_jigyosyo_exists_koyou_sekininsha",
    label: "事業所に雇用責任者が存在するか",
    isDisplay: true,
  },
  {
    name: "_jigyosyo_is_use_kaigo_machine_subsidy",
    label: "介護機器助成金の使用",
    isDisplay: true,
  },
  {
    name: "_jigyosyo_is_use_other_subsidy",
    label: "その他の助成金の使用",
    isDisplay: true,
  },
  {
    name: "_management_description",
    label: "雇用管理者専任状況",
    isDisplay: true,
    type: "text",
  },
  {
    name: "_management_is_sanjo",
    label: "賛助会員",
    isDisplay: true,
    type: "checkbox",
  },
].map((field) => ({
  ...field,
  groupId: field.sLabelGroup || field.groupId,
}));
