# Generated by Django 4.2.5 on 2023-10-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigyosyo',
            name='action_type',
            field=models.CharField(choices=[('merge', 'Merge'), ('split', 'Split'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='jigyosyo',
            name='related_jigyosyos',
            field=models.ManyToManyField(blank=True, related_name='related_to_%(class)s', to='crm.jigyosyo'),
        ),
        migrations.AddField(
            model_name='jigyosyo',
            name='rule_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
